on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            archive: tar.gz tar.xz

    steps:
      - uses: actions/checkout@master
      - name: Installing needed dependencies
        run: sudo apt install -y libsqlite3-mod-spatialite build-essential
      - uses: actions/setup-go@v3
      - name: Running go build
        run: go build -o bin/mada
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Packaging final binary
        shell: bash
        run: |
          tar czvf mada_${{ env.RELEASE_VERSION }}_${{ matrix.target }}.tar.gz bin/mada
          shasum -a 256 mada_${{ env.RELEASE_VERSION }}_${{ matrix.target }}.tar.gz > mada_${{ env.RELEASE_VERSION }}_${{ matrix.target }}.tar.gz.sha256
      - name: Releasing assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            mada_${{ env.RELEASE_VERSION }}_${{ matrix.target }}.tar.gz
            mada_${{ env.RELEASE_VERSION }}_${{ matrix.target }}.tar.gz.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}